fix: Fixes parsing of boolean environment variables
interledger/five-bells-wallet pull request #168
Opened 2017-01-06 15:04 UTC by dappelt

If a environment varialbe was set to the literal false, it was treated as being set to true.

2017-01-06 15:21 UTC, sharafian requested changes

2017-01-06 15:21 UTC, sharafian commented on bin/normalizeEnv.js
> +  } else if (val === '') { // if the varialbe is undefined
varialbe -> variable

2017-01-06 15:21 UTC, sharafian commented on bin/normalizeEnv.js
> +  throw {_error: 'Can not parse as boolean: ' + name}
This should trigger `process.exit(1)`, like it does [here](https://github.com/interledgerjs/ilp-kit/pull/168/files#diff-3641b3524271ca689c53abb4d4a7e8a4R55)

2017-01-06 18:22 UTC, vhpoet commented
@dappelt five-bells-shared already has code for this https://github.com/interledgerjs/five-bells-shared/blob/master/lib/config.js#L42-L63

2017-01-06 18:26 UTC, vhpoet requested changes
@dappelt five-bells-shared already has code for this https://github.com/interledgerjs/five-bells-shared/blob/master/lib/config.js#L42-L63, please use that instead.

2017-01-09 10:11 UTC, dappelt commented
done

2017-01-09 10:19 UTC, sharafian approved these changes

2017-01-09 19:07 UTC, vhpoet approved these changes

2017-01-10 09:39 UTC, merged